Project 4: Building with Backgrounds and Gradients
julian3493/old-apple-page pull request #1
Opened 2020-09-24 20:55 UTC by Jarfsoft

## Old Apple Page Clone
- Navigation Bar located with position absolute.
- Added background image to the main section.
- Used grid for the 4 pictures below the main section.
- Footer divided with the copyright and the useful links.

2020-09-24 22:10 UTC, teekaytech requested changes
## Status: Changes Required :warning::vertical_traffic_light: 

### Hello @julian3493 & @Jarfsoft :wave: 

**I must say, you guys have done an awesome job right here :clap:**
- Your linters are green :green_circle: 
- Proper use of CSS grid / flex :100: 
- Nice application of background gradient :+1: 
- Use of semantic tags :ok_hand: 

**Overall, this is looking good. However, there are some issues we need to fix before this project can be approved. Let's get to it:**

**[ REQUIRED CHANGES ]**

- [x] The background image must cover the whole page, no matter the screen size. 
- There is white space around your page. It looks like this is caused by a default margin set by the browser on your `<body>` tag. Kindly find a way to remove this space.

![23:01:33](https://user-images.githubusercontent.com/26856491/94204834-ed306c80-feb9-11ea-9c6a-88758b3174d2.png)

![22:55:53](https://user-images.githubusercontent.com/26856491/94204424-23212100-feb9-11ea-8d68-b44e8e114cfa.png)

- [ ] Each cell in the grid section of the page (4 columns) should be linked. 

![23:04:51](https://user-images.githubusercontent.com/26856491/94205081-629c3d00-feba-11ea-8ea2-21cc68aac1b4.png)

![23:05:34](https://user-images.githubusercontent.com/26856491/94205120-79429400-feba-11ea-9af5-ca34cf1d9095.png)

- [x] Your page is having a horizontal scroll bar. Kindly identify which of your containers is causing this and remove it.

**Kindly make the required changes and request for another review when you are done.**

*__You can reach out to me on slack (@taofeekolalere) or GitHub (@teekaytech).__*

**Happy coding. :man_technologist:**

2020-09-24 22:10 UTC, teekaytech commented on index.html
> +    <title>Document</title>
**Optional**
It's not a bad thing to give your project a befitting title. Please change the title of the project.

2020-09-24 22:10 UTC, teekaytech commented on index.html
> +            <a href="#"><img class="lang-icon" src="assets/img/apple.png" alt=""></a>
Always give your image tags their corresponding `alt` attribute and value. Kindly fix this.

2020-09-24 23:01 UTC, jubaan requested changes
# Status: Changes Required :recycle:

## :wave: :wave: Hello Team!! I've see you have done great! :clap: :clap:

## Required Changes

### [Mandatory] :red_circle: 

- [ ] Please work on the suggested changes asked for the previous TSE
-  **The background image must cover the whole page, no matter the screen size.**
- **Each cell in the grid section of the page (4 columns) should be linked.**

- [ ] Update the link to live preview in the README. This should fix all previous issues.

- [ ] ```<main>``` section should wrap also the 4 bottom images.

### [OPTIONAL]  :large_blue_circle: 

- [ ] Try to use 2 space indentation in HTML and CSS file. This improves readability.

- [ ] Prefer specific CSS selectors over the more general ones.  This improves readability as it assigns meaningful selector names, and this makes it easier to debug. Example:
**Actual**
```
nav a,`
nav input {
   ... some properties ...
}
```
**Improved** :+1: :
```
.nav__link,
.nav__search {
   ... some properties ...
}
```

### [Comments] :green_circle: 

- The README is the most important file of the project, as it describes the project, is important to maintain it updated.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-09-25 00:29 UTC, jubaan approved these changes
# Status: Approved :tada: :tada: :tada:

## :clap: :clap: Nice Team!

You've may now merge to master!

### [Comments] :green_circle: 
The page still has a horizontal scroll on smaller screen sizes but because is related to responsiveness is out of the scope of this project goals. 

Still, it is good to mention because this will be an issue for latter projects. Make a habit of using the browsers media queries inspector. This will help you identify if the project looks correct in different screen sizes. Keep in mind that the users may not have the same screen size as the programmer.

An idea to identify the issue of the scrolling horizontal bar: 
![image](https://user-images.githubusercontent.com/25774518/94213094-a03d9d80-fe9b-11ea-8dd3-b14c50e6729d.png)

## See you at the top :rocket:!

2020-09-25 00:38 UTC, merged